library(gridExtra)
library(png)
library(grid)
img1 <- readPNG("filter_tests10.png")
img2 <- readPNG("filter_tests10v2.png")
img3 <- readPNG("filter_tests10v3.png")
img4 <- readPNG("filter_tests10v4.png")
img5 <- readPNG("filter_tests10v6.png")
img6 <- readPNG("filter_tests10v7.png")
img7 <- readPNG("filter_tests10v8.png")
img8 <- readPNG("filter_tests10v9.png")
img9 <- readPNG("filter_tests10v10.png")
img10 <- readPNG("filter_tests10v11.png")

g1 <- rasterGrob(img1, interpolate=TRUE)
g2 <- rasterGrob(img2, interpolate=TRUE)
g3 <- rasterGrob(img3, interpolate=TRUE)
g4 <- rasterGrob(img4, interpolate=TRUE)
g5 <- rasterGrob(img5, interpolate=TRUE)
g6 <- rasterGrob(img6, interpolate=TRUE)
g7 <- rasterGrob(img7, interpolate=TRUE)
g8 <- rasterGrob(img8, interpolate=TRUE)
g9 <- rasterGrob(img9, interpolate=TRUE)
g10 <- rasterGrob(img10, interpolate=TRUE)

pdf("ft10_comparison.pdf", width=8, height=11)
grid.arrange(g1, g2, g3, g4, nrow=2, ncol=2)
grid.arrange(g5, g6, g7, g8, nrow=2, ncol=2)
grid.arrange(g9, g10, nrow=2, ncol=2)
dev.off()